export const API_HOST = process.env.REACT_APP_API_URL || 'http://buma-business-manager.herokuapp.com/';
export const ERROR_URL = '/mobile/#/error';
export const TECH_APP_URL = 'http://web.kwik.me/techApp';
export const REDIRECT_URL = 'http://127.0.0.1';
export const NEW_USER_JOURNEY = 'NEW_USER_JOURNEY';
export const RETURNING_USER_JOURNEY = 'RETURNING_USER_JOURNEY';
export const EDIT_ORDER_JOURNEY = 'EDIT_ORDER_JOURNEY';
export const CATEGORY_ALL = '*';
export const ACTION_COLOR = '#223791';
export const TEACH_WIFI_RESULT_SCREEN_SUCCESS_TITLE =  'Button Connected!';
export const TEACH_WIFI_RESULT_SCREEN_SUCCESS_TITLE_IPM =  'Trap Connected!';
export const TEACH_WIFI_RESULT_SCREEN_FAIL_TITLE =  'Connection failed';
export const SEARCH_DELAY = 550;
export const MAX_CUSTOMER_NAME_DISPLAY_LEN = 36;
export const IPM_PROJECT_ID1 = '594fa753f95d22178f7e8226'
export const IPM_PROJECT_ID2 = '5909d0beb244b8449f4b6ede'
export const BUTTON_SERIAL_LENGTH = 7
